zazuko/trifid

- views/error.html
- views/home.html
- views/index.html
`header.html`, `navigation.html` and `footer.html` are currently loaded from the `cwd`, which enforces making copies of the views to a project which uses Trifid as a dependency, even if no changes are made. This PR changes `index.html`, `error.html` and `home.html` to use `header.html`, `navigation.html` and `footer.html` from the `trifid` folder. This was a bug, as Trifid should run just with a config or even without config, if a SPARQL endpoint is used. But the bug could have been used to change only the `header.html`, `navigation.html` and `footer.html` views without copying `index.html`, `error.html` and `home.html`. After merging this PR customizing the views requires to copy all views to the project folder, which uses Trifid as dependency.
> load views from trifid folder and not cwd

- README.md
Adds information how to use the `env:` prefix in the config and infos about the command line program and parameters.
> Add env prefix and cli to Readme

- README.md
- config-fetch.json
- config.json
- package.json
@bergos Trifid has a lot of dependencies, I guess some of them are only there to have the examples run or for the default config.
If you know which ones are not 100% necessary, we could move them to peer dependencies and it'd be up to the people who depend on trifid to install the ones they actual need?
> Replace trifid-handler-fs with trifid-handler-fetch

- LICENSE
- README.md
- package.json
- server.js
Using `trifid:` as root namespace to get logs with `trifid:*`
> better debug logging

- config-sparql.json
Together with https://github.com/zazuko/trifid-plugin-yasgui/pull/2 , fixes https://github.com/zazuko/trifid/issues/76
---
I'll merge and publish after trifid-plugin-yasgui is published and trifid-plugin-yasgui version is updated in `config-sparql.json`
> Use zazuko URL shortener in yasgui plugin config

- Dockerfile
- Tutorial.md
- server.js
In the past it was possible to set the config file path using the `TRIFID_CONFIG` environment variable in the docker setup. That was done with some env expansion in the dockerfile. This re-adds this feature, but extends it to the node app itself.
Also uses `tini` as PID1 instead of npm start, see https://www.elastic.io/nodejs-as-pid-1-under-docker-images/
> Load config file from env

- .github/workflows/docker.yaml
- Dockerfile
- config-docker.json
- server.js
Closes #106 
The following Docker image is created using GitHub Actions: `ghcr.io/zazuko/trifid`
It supports the following architectures:
- amd64
- arm64
Here are some environment variables that can be used to configure the Docker image:
- `SPARQL_ENDPOINT_URL`: configure the SPARQL endpoint
- `DATASET_BASE_URL`: configure the dataset base URL
- `SPARQL_USER`: the user to authenticate against the SPARQL endpoint
- `SPARQL_PASSWORD`: the password to authenticate against the SPARQL endpoint
If you need to override some configuration, you can mount a file in the `/app` directory in the Docker image, and set the `TRIFID_CONFIG` environment variable to point to the file, relatively to the `/app` directory.
> Improve Docker image

- .github/workflows/test.yaml
Since Node 16 is dead, we don't have to support it anymore.
This removes the tests using Node 16, so that we are not running useless runners.
> Remove tests using Node 16

- .changeset/clever-snakes-judge.md
- .changeset/olive-dogs-reply.md
- packages/core/middlewares/errors.js
- packages/core/test/middlewares/errors.test.js
- packages/entity-renderer/renderer/labels/labelLoader.js
- packages/entity-renderer/test/entity-renderer.test.js
This PR is doing the following:
- send an empty body message in case of error, this fix some unexpected issues with the use of `hijackresponse` (that we will try to remove in the future)
- fix an issue in entity renderer plugin for the label loader, where the `forEach` method is not available due to the replacement of `rdf-ext` with `@zazuko/env`
- improve tests for the entity renderer: it's now able to check if it is rendered as HTML also
> Improve tests and fix some bugs

- .changeset/warm-seas-brush.md
- packages/ckan/README.md
- packages/ckan/src/index.js
- packages/ckan/src/namespace.js
- packages/ckan/src/xml.js
- packages/ckan/test/ckan.test.js
- packages/ckan/test/support/basic-result.xml
This PR converts legacy frequencies to EU frequencies, as required here: https://handbook.opendata.swiss/fr/content/glossar/bibliothek/dcat-ap-ch.html#dct-accrual-periodicity-dcat.
> CKAN: Convert legacy frequency to EU frequency

- .github/workflows/docker.yaml
This PR replace the use of our custom action with the `docker/metadata-action` GitHub Action.
> Use `docker/metadata-action` GitHub Action

- .changeset/cuddly-vans-pay.md
- .github/workflows/docker.yaml
- package-lock.json
- package.json
- packages/core/package.json
- packages/trifid/Dockerfile
- packages/trifid/package.json
This upgrades the base for the Docker image from Node 18 to Node 20, as it's the latest LTS version.
This also upgrades some dependencies and sets the minimal required node version to node 18 (as we removed tests for previous versions).
> Use node 20 as base of the Docker image

- .changeset/famous-pumpkins-work.md
- packages/markdown-content/src/index.js
Use 'markdown-content-' as id prefix, instead of 'content-'.
> Change default prefix

- .changeset/dry-seals-marry.md
- packages/markdown-content/README.md
- packages/markdown-content/src/index.js
- packages/markdown-content/test/index.test.js
Since the rendered version is HTML, it makes no sense to have `markdown` in the prefix of the generated IDs for content headings.
Users can configure the prefix to use by using the `idPrefix` option.
See the README.md file for more information on how to use this configuration option.
> Change default prefix to `content-`

- .changeset/stale-humans-grow.md
- packages/entity-renderer/index.js
We experienced the same issue as https://github.com/zazuko/trifid/issues/169 using eclipse/rdf4j-workbench. An nq file was downloaded instead of displaying the subject page.
The cause of this issue is that the response from the sparql endpoint is re-used. Rdf4j workbench adds the following header to this response: 
`Content-Disposition: attachment; filename=query-result.nq`
This header causes the browser to download the response instead of displaying the html result from the entity-renderer. I assume that Blazegraph (as in issue https://github.com/zazuko/trifid/issues/169 and https://github.com/zazuko/trifid/issues/170) does the same.
> entity-renderer: remove content-disposition from response

- .changeset/sharp-brooms-dream.md
- .github/workflows/test.yaml
- package-lock.json
- packages/ckan/.gitignore
- packages/ckan/package.json
- packages/ckan/tsconfig.json
I found that type declarations are not checked in CI. Also, the CKAN plugin did not have typescript set up at all
I'd like to merge this before #257
> ci: add step to check types

- .changeset/fluffy-pillows-dance.md
- .changeset/kind-apples-shout.md
- .changeset/pink-mails-jog.md
- .changeset/seven-horses-brake.md
- packages/ckan/src/namespace.js
- packages/ckan/src/query.js
- packages/ckan/src/xml.js
- packages/ckan/test/ckan.test.js
- packages/ckan/test/support/basic-result.xml
- packages/ckan/test/support/data.ttl
Re #280
Properties of `dcat:Dataset`:
- `publisher`: import format changed ; see: https://handbook.opendata.swiss/de/content/glossar/bibliothek/dcat-ap-ch.html#dcat-dataset-publisher
- `theme`: new vocabulary to use ; see: https://handbook.opendata.swiss/de/content/glossar/bibliothek/dcat-ap-ch.html#dcat-dataset-theme
- `landing page`: import format changed ; see: https://handbook.opendata.swiss/de/content/glossar/bibliothek/dcat-ap-ch.html#dcat-dataset-landing-page
- `accrual periodicity`: import format changed ; see: https://handbook.opendata.swiss/de/content/glossar/bibliothek/dcat-ap-ch.html#dcat-dataset-accrual-periodicity
- `related resource`: mandatory for federal level, the legal basis must be indicated here ; see: https://handbook.opendata.swiss/de/content/glossar/bibliothek/dcat- …
> Update some CKAN properties

- .changeset/lazy-lemons-protect.md
- packages/ckan/src/query.js
- packages/ckan/test/support/data.ttl
Related to https://gitlab.ldbar.ch/pipelines/open-data-swiss/-/merge_requests/10, I also change the code to handle the explicit `schema:supersededBy` which separates old and new categories
> refactor: explicitly annotated deprecated categories

- .changeset/fifty-pillows-carry.md
- packages/sparql-proxy/index.js
This is fixing an issue with the rewrite query parameter, where it was assuming that an undefined value was equal to 'true' in all cases.
> Fix wrong value for rewrite query parameter

- .changeset/curvy-poems-sort.md
- .changeset/ninety-birds-type.md
- packages/core/lib/handlers/notFound.js
- packages/core/lib/templateEngine.js
- packages/core/plugins/view.js
- packages/core/types/index.js
- packages/entity-renderer/index.js
- packages/graph-explorer/index.js
- packages/markdown-content/src/index.js
- packages/spex/index.js
- packages/yasgui/index.js
This change allows the renderer to get information about the session.
This is required to properly support multilingual instances, for example.
> Internal `render` function requires the request as first argument

- .changeset/wise-flies-know.md
- packages/core/plugins/locals.js
For multilingual instances, it was setting a cookie only on the current page.
This was a strange behavior in terms of UX.
> `locals` should use cookies path set to `/`

- .changeset/heavy-kiwis-matter.md
- packages/core/lib/sparql.js
This allows Trifid plugins to send custom headers to the SPARQL endpoint when they use the `query` function provided by Trifid.
> Allow to send custom headers in `query` function

- .changeset/two-rats-bow.md
- packages/entity-renderer/index.js
- packages/entity-renderer/renderer/entity.js
- packages/entity-renderer/renderer/labels/labelLoader.js
For each request made to the SPARQL endpoint, a `i18n` cookie that contains the value of the current language will be sent.
This is helping to prevent some issues for multilingual instances.
> Add `i18n` cookie to requests made to the SPARQL endpoint

- .changeset/mighty-items-behave.md
- packages/core/index.js
Add support for `application/sparql-query` content type.
This allows queries to be sent directly as the body of an HTTP request.
> Add support for `application/sparql-query` content type

- .changeset/beige-lemons-hear.md
- .changeset/thirty-steaks-ring.md
- packages/entity-renderer/index.js
Querying quads from the entity renderer allow getting the right graph names, so that they can be displayed on the dereferenced entity.
> Query quads

- .changeset/eighty-mirrors-pump.md
- packages/sparql-proxy/README.md
- packages/sparql-proxy/index.js
- packages/trifid/instances/docker-sparql/config.yaml
This allows users to specify a `format` query parameter to force the endpoint to deliver the response in a particular format.
The SPARQL endpoint should be able to support the requested format.
> New `formats` configuration field for sparql-proxy

- .github/workflows/test.yaml
This removes the tests for the two plugins that were deleted recently:
- redirects
- handler-sparql
> Remove tests for old plugins

- .github/workflows/test.yaml
Jobs for tests using Node 18 seems to be in trouble, and we are using too many jobs in parallel.
> Disable node 18 for tests

- .changeset/rare-forks-hear.md
- packages/yasgui/README.md
- packages/yasgui/index.js
- packages/yasgui/views/yasgui.hbs
As requested in #334, it can be useful to be able to configure the default query for the YASGUI plugin.
This PR adds this feature.
> Configure `defaultQuery` for YASGUI

- .changeset/fuzzy-dingos-hide.md
- package-lock.json
- packages/entity-renderer/index.js
- packages/entity-renderer/package.json
This uses the `mimeparse` module to support complex Accept headers.
Improvement for #362, as suggested by @ktk.
> Use `mimeparse` to parse Accept headers

- .changeset/two-gifts-reflect.md
- packages/entity-renderer/README.md
- packages/entity-renderer/index.js
This adds the `additionalRewrites` configuration option.
It can be useful in case rewrite is enabled but that default rules are not enough.
> Add `additionalRewrites` configuration option

- .changeset/nine-fireants-press.md
- Dockerfile
This improves the default health check configured for the Docker image, in order to mark it as healthy faster.
If a specific Trifid instance needs more time to be started, it can always be possible to override this configuration.
> Faster health checks for the Docker image

- .changeset/late-papayas-smell.md
- .changeset/sweet-ducks-worry.md
- packages/handler-fetch/index.js
- packages/sparql-proxy/index.js
Returns `Server-Timing` as response header containing the duration of the request to perform, for the sparql-proxy and for the handler-fetch Trifid plugins.
> Send Server-Timing responses for SPARQL query responses

- .github/workflows/test.yaml
Since Node 22 will be the new LTS version soon (end of October), it could be great to make sure that everything is already ready for that version.
This PR is enabling the run of the tests on Node 22 in addition of the current Node 20.
> Run tests using Node 22 also

- .changeset/gold-peaches-smile.md
- packages/sparql-proxy/README.md
- packages/sparql-proxy/index.js
This PR allows the configuration of the query log level for the `sparql-proxy` Trifid plugin.
> [sparql-proxy] Configure query log level

- .changeset/gorgeous-apes-prove.md
- packages/handler-fetch/README.md
- packages/handler-fetch/index.js
This PR allows the configuration of the query log level for the `handler-fetch` Trifid plugin.
It is done in a similar way as for the `sparql-proxy` (work done in #446).
> [handler-fetch] Configure query log level

- .changeset/fresh-avocados-reply.md
- packages/core/config.yaml
- packages/core/index.js
- packages/core/lib/config/default.js
- packages/core/lib/config/schema.json
- packages/core/types/index.js
- packages/entity-renderer/examples/config/trifid.yaml
This adds the following configuration option: `server.logFormat`.
It can take one of the following value:
- `pretty` (default): use [`pino-pretty`](https://github.com/pinojs/pino-pretty) to display logs in a pretty format, ideal for development
- `json`: great for production, as it is easier to parse by using some scripts or other tools
> [core] Add `server.logFormat` configuration option

- .changeset/lovely-months-mix.md
- packages/entity-renderer/README.md
- packages/entity-renderer/index.js
This adds a `enableSchemaUrlRedirect` configuration option.
If set to `true`, the plugin will perform a redirect if the URI contains a `schema:URL` predicate pointing to a resource of type `xsd:anyURI`.
The default value is `false`.
> Add `enableSchemaUrlRedirect` config option

- .changeset/proud-donkeys-exercise.md
- packages/sparql-proxy/index.js
With the previous release, we were hit by an issue that prevented the `sparql-proxy` plugin to use streams if compression was requested, and we temporarily replaced them with awaited strings.
The issue with this was that responses were a bit slower as the plugin was waiting to get the full data from the endpoint before sending it to the client.
Also, in terms of memory usage, it was not ideal.
Using the workaround given in https://github.com/fastify/fastify-compress/issues/309#issuecomment-2303563647 seems to solve the issue.
There was just an issue in terms of types that were reported ; as it behaves correctly, I just disabled the type error by using a cast to `any` for the `responseStream` variable.
> Add stream support back

- packages/core/index.js
Closes: #472
see https://www.npmjs.com/package/fastify-compress/v/1.0.0#options
> fix: add custom compressible `mime-types`

- .changeset/cuddly-colts-camp.md
- packages/yasgui/plugins/map.js
This improves the Map plugin icon.
It uses an SVG instead of the unicode character.
This delivers a more consistent look and feel across all kind of devices and operating systems.
> Improve the Map plugin icon

- .changeset/odd-geese-beg.md
- package-lock.json
- packages/yasgui/README.md
- packages/yasgui/index.js
- packages/yasgui/package.json
- packages/yasgui/plugins/deps.js
- packages/yasgui/plugins/map.js
- packages/yasgui/plugins/style.js
- packages/yasgui/views/yasgui.hbs
I propose to replace the map bundle with our own where we import what's necessary.
> refactor: bundle maps ourselves

- .changeset/tasty-ladybugs-retire.md
- packages/entity-renderer/README.md
- packages/entity-renderer/index.js
If `enableSchemaUrlRedirect` configuration option is set to `true`, the plugin is performing a redirect if the URI contains a `schema:URL` predicate pointing to a resource of type `xsd:anyURI` (already in place).
The user can now disable this behavior by either:
- setting the `disableSchemaUrlRedirect` query parameter to `true`
- setting the `x-disable-schema-url-redirect` header to `true`
> Let the user disable schema url redirects if enabled

- .changeset/strong-hounds-judge.md
- packages/graph-explorer/views/graph-explorer.hbs
This adds integrity hash to external resources.
> Add integrity hash to external resources

- .changeset/cyan-laws-scream.md
- packages/entity-renderer/index.js
Expose `jsonld` string to the view, so that some complex logic could be done on top of it if needed.
> Expose `jsonld` string to the view

- packages/i18n/package.json
- packages/i18n/test/test.js
Migrate this simple i18n plugin to native node test runner.
> Migrate i18n to node test

- package-lock.json
- packages/ckan/package.json
- packages/ckan/test/ckan.test.js
- packages/ckan/tsconfig.json
- packages/core/package.json
- packages/core/test/config.test.js
- packages/core/types/index.d.ts
- packages/graph-explorer/.npmignore
- packages/graph-explorer/package.json
- packages/graph-explorer/tsconfig.json
- packages/handler-fetch/package.json
- packages/markdown-content/package.json
- packages/sparql-proxy/package.json
- tsconfig.json
Upgrade a few dependencies, and migrate ckan plugin to use node:test.
> Upgrade various dependencies

- .changeset/funny-teachers-promise.md
- packages/ckan/src/index.js
- packages/entity-renderer/index.js
- packages/graph-explorer/index.js
- packages/iiif/index.js
- packages/sparql-proxy/index.js
- packages/spex/index.js
Fix `requestPort` value, to handle `null` cases and simplify the logic.
> Handle null requestPort

- .changeset/odd-spiders-notice.md
- packages/yasgui/views/yasgui.hbs
Before it was using `superagent` included with Yasgui editor, which is now not included anymore.
> Use standard `fetch` to shorten URLs

- packages/sparql-proxy/test/index.test.js
Using tests on external resources can make the pipeline fail if the end resource is not available, which is not something we want.
I removed the tests in the `sparql-proxy` plugin that were targeting DBpedia.
Example of failed pipeline: https://github.com/zazuko/trifid/actions/runs/11886907613/job/33118804561
> sparql-proxy: remove tests on external resources

- README.md
The README was still showing very old default environment variable names.
This PR updates the README file to show the new one to use.
Thank you @tpluscode for reporting the issue!
> [README] Fix environment variables to use

- package-lock.json
- package.json
- packages/ckan/src/namespace.js
- packages/ckan/src/query.js
- packages/ckan/src/xml.js
- packages/core/lib/sparql.js
I needed to remove the `namespaces.js` file for the CKAN plugin, and change the imports for the other files.
For the `core` module, I also made sure that headers are sent as an object.
> Upgrade TypeScript to 5.7.2

- .changeset/loud-guests-attack.md
- .changeset/tall-plums-type.md
- package-lock.json
- packages/core/package.json
- packages/core/test/config.handler.test.js
- packages/core/test/config.test.js
- packages/core/test/plugins/health.test.js
- packages/core/test/plugins/redirect.test.js
- packages/core/test/plugins/static.test.js
- packages/core/test/plugins/throw.test.js
- packages/core/test/plugins/view.test.js
- packages/core/test/resolvers.test.js
- packages/entity-renderer/README.md
- packages/entity-renderer/index.js
- packages/sparql-proxy/README.md
- packages/sparql-proxy/index.js
- packages/sparql-proxy/lib/fetchServiceDescription.js
- packages/sparql-proxy/lib/serviceDescriptionWorker.js
- packages/sparql-proxy/lib/utils.js
- packages/sparql-proxy/package.json
- packages/sparql-proxy/test/ReplaceStream.test.js
- packages/sparql-proxy/test/index.test.js
- packages/sparql-proxy/test/mocha_setup.js
- packages/sparql-proxy/test/support/failingWorker.js
- packages/sparql-proxy/test/support/workerDouble.js
- packages/sparql-proxy/test/utils.test.js
This allows configuring multiple endpoints in the `sparql-proxy`, and use a specific endpoint from the `entity-renderer` plugin if the `allowEndpointSwitch` configuration option is set to `true`.
> Multi endpoint support

- .changeset/three-berries-perform.md
- packages/entity-renderer/index.js
- packages/entity-renderer/lib/base.js
- packages/entity-renderer/lib/config.js
- packages/entity-renderer/lib/headers.js
- packages/entity-renderer/test/base.test.js
- packages/entity-renderer/test/headers.test.js
Add support for multiple `datasetBaseUrl`.
It can be defined as a string (for a single value), or as an array of strings.
> Entity renderer: add support for multiple `datasetBaseUrl`

- .changeset/cruel-worlds-juggle.md
- package-lock.json
- packages/yasgui/package.json
This bumps the `@zazuko/yasgui` module to 4.5.0.
> Bump `@zazuko/yasgui` to 4.5.0

- .github/workflows/release.yaml
- .github/workflows/test.yaml
This makes sure that we always test against the current LTS version of Node.JS.
> Use latest LTS version of Node.JS in CI

- .changeset/green-seas-smoke.md
- packages/entity-renderer/index.js
- packages/entity-renderer/lib/base.js
- packages/entity-renderer/test/base.test.js
This just adds support for the previous behavior back, where it was possible to run Trifid without specifying a `databaseBaseUrl` value.
> Add support for empty `datasetBaseUrl` back

- .changeset/violet-corners-learn.md
- packages/sparql-proxy/README.md
- packages/sparql-proxy/index.js
- packages/sparql-proxy/lib/fetchServiceDescription.js
- packages/sparql-proxy/lib/serviceDescriptionWorker.js
This allows to send custom headers to the endpoint.
This is useful in case some users needs to use Bearer tokens (as mentioned in #673), …
> Add `headers` option

- .changeset/thin-hotels-doubt.md
- packages/core/package.json
The Docker container version was working as expected, but if a user was trying to import the `trifid-core` module using NPM he got the `otel.js` module is not found.
This should solve this issue.
> Fix(core): include `otel.js`

- .changeset/quick-geckos-draw.md
- packages/entity-renderer/index.js
- packages/handler-fetch/index.js
- packages/sparql-proxy/index.js
The current implementation could theoretically explode the number of generated metrics.
This PR tries to find the right balance.
> Reduce OpenTelemetry cardinality
