zazuko/trifid

package.json

Upgrade sparql-proxy

---

Dockerfile

This PR only has the Dockerfile rewrite. The Kubernetes setups will be in another repo.

Dockerfile rewrite

---

.eslintrc
Dockerfile
package.json
server.js

This PR adds support for NodeJS 16 and upgrade some dependencies.

Add support for Node 16

---

.changeset/metal-mails-wash.md
package-lock.json
packages/sparql-proxy/README.md
packages/sparql-proxy/index.js
packages/sparql-proxy/package.json

sparql-proxy: add support for proxies

---

.changeset/dirty-hats-sin.md
.eslintrc.json
package-lock.json
package.json
packages/redirects/index.js

Redirects: add support for 2006 and some fixes

---

.github/workflows/add-to-backlog.yml
.github/workflows/docker.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

This PR upgrades multiple GitHub Actions.

Upgrade GitHub Actions

---

.changeset/three-ladybugs-behave.md
packages/ckan/src/xml.js
packages/ckan/test/support/basic-result.xml

CKAN: use `rdf:datatype` instead of `xml:datatype`

---

.changeset/honest-clouds-clean.md
packages/ckan/src/query.js
packages/ckan/src/xml.js
packages/ckan/test/support/basic-result.xml
packages/ckan/test/support/data.ttl

CKAN: Improve the way frequencies are handled

---

.changeset/pink-worms-suffer.md
packages/entity-renderer/renderer/metadata/namedGraphs.js
packages/entity-renderer/renderer/web-component/N3Term.js

Show graph name label

---

.changeset/big-trainers-run.md
.changeset/six-pets-draw.md
.changeset/tough-deers-study.md
packages/markdown-content/README.md
packages/markdown-content/src/index.js
packages/markdown-content/test/index.test.js
packages/markdown-content/test/support/custom.hbs

Configure autoLink, idPrefix, custom classes and other options.

---

.changeset/olive-otters-press.md
package-lock.json
packages/markdown-content/README.md
packages/markdown-content/src/index.js
packages/markdown-content/src/utils.js
packages/markdown-content/test/index.test.js

Support multiple entries

---

.changeset/ten-coats-jam.md
package-lock.json
packages/ckan/package.json
packages/ckan/src/ckan.js
packages/ckan/src/namespace.js
packages/ckan/src/query.js
packages/ckan/src/xml.js
packages/ckan/test/ckan.test.js
packages/ckan/test/support/data.ttl

I finally found that the problem with `dcat:contactPoint` is additional RDF types. The code to serialize expected only one to wrap in `<vcard:Organization>` node for example.
I made this explicit to ignore other types and only consider `vcard:Individual` and `vcard:Organization`

fix: contact point

---

.changeset/kind-apples-shout.md
packages/ckan/src/namespace.js
packages/ckan/src/xml.js
packages/ckan/test/support/basic-result.xml
packages/ckan/test/support/data.ttl

https://handbook.opendata.swiss/fr/content/glossar/bibliothek/dcat-ap-ch.html#dcat-dataset-documentation
I think the docs are incorrect. To be confirmed with Michele

foaf:page - dataset documentation

---

.changeset/young-beers-relate.md
packages/markdown-content/src/index.js

Content is stored in session instead of locals.

Use session to store content

---

.changeset/happy-kids-tap.md
packages/yasgui/views/yasgui.hbs

Update the link to the GitHub repository.

Update plugin repo link

---

.changeset/thick-snakes-fix.md
packages/yasgui/README.md
packages/yasgui/index.js
packages/yasgui/package.json
packages/yasgui/test/test.js
packages/yasgui/views/yasgui.hbs

This is the implementation for #92.

Add `catalog` option

---

.changeset/twelve-rules-trade.md
package-lock.json
packages/yasgui/package.json

This upgrades YASGUI to version 4.3.0.

Upgrade YASGUI to 4.3.0

---

package-lock.json
packages/iiif/index.js
packages/iiif/package.json

Import `@zazuko/env` instead of `rdf-ext`.

Fix `rdf` import for IIIF plugin

---

.changeset/new-pandas-hide.md
packages/entity-renderer/index.js

Add support for complex accept headers

---

.changeset/flat-glasses-breathe.md
.changeset/long-seahorses-eat.md
package-lock.json
packages/ckan/src/index.js
packages/core/index.js
packages/core/package.json
packages/core/plugins/health.js
packages/core/plugins/redirect.js
packages/core/plugins/view.js
packages/entity-renderer/index.js
packages/graph-explorer/index.js
packages/handler-fetch/index.js
packages/iiif/index.js
packages/markdown-content/src/index.js
packages/sparql-proxy/index.js
packages/spex/index.js
packages/yasgui/index.js

Enable compression support

---

.changeset/tidy-hornets-explain.md
packages/core/index.js

fix: compress `text/turtle`

---

.github/workflows/codeql.yaml

Configure CodeQL

---

.changeset/kind-dryers-give.md
packages/ckan/package.json
packages/core/package.json
packages/entity-renderer/package.json
packages/graph-explorer/package.json
packages/handler-fetch/package.json
packages/i18n/package.json
packages/iiif/package.json
packages/markdown-content/package.json
packages/sparql-proxy/package.json
packages/spex/package.json
packages/trifid/package.json
packages/yasgui/package.json

Many packages were not defining the author and/or the keywords fields in the package.json file.
This PR fixes this.

Harmonize author and keyword fields

---

.changeset/slimy-moons-suffer.md
packages/yasgui/index.js

Fix `requestPort` value, to handle `null` cases.

Handle null requestPort

---

.changeset/honest-hairs-learn.md
.changeset/silly-forks-retire.md
package-lock.json
packages/ckan/package.json
packages/ckan/src/index.js
packages/graph-explorer/index.js
packages/graph-explorer/package.json
packages/handler-fetch/index.js
packages/i18n/index.js
packages/markdown-content/package.json
packages/markdown-content/src/index.js
packages/sparql-proxy/index.js
packages/sparql-proxy/package.json
packages/sparql-proxy/tsconfig.json
packages/spex/index.js
packages/yasgui/index.js
tsconfig.json

This exports types for the sparql-proxy plugin and fix and improve the types for some other plugins.

Export types for sparql-proxy plugin

---

.changeset/shaggy-boxes-love.md
package-lock.json
packages/yasgui/package.json

This PR upgrades Yasgui to v4.4.1.

Upgrade Yasgui to 4.4.1

---

.changeset/quick-spies-speak.md
package-lock.json
package.json
packages/ckan/package.json
packages/ckan/src/index.js
packages/core/package.json
packages/graph-explorer/index.js
packages/graph-explorer/package.json
packages/handler-fetch/index.js
packages/handler-fetch/package.json
packages/i18n/index.js
packages/markdown-content/src/index.js
packages/sparql-proxy/index.js
packages/sparql-proxy/package.json
packages/spex/index.js
packages/spex/package.json
packages/yasgui/index.js
packages/yasgui/package.json

This upgrades some dependencies.

Upgrade dependencies
